version: "3.4"
services: 
    app:
        image: node:8-alpine
        container_name: rbs-app
        volumes: 
            - type: bind
              source: ./
              target: /usr/app
            - type: volume
              source: nodemodules
              target: /usr/app/node_modules
              volume:
                nocopy: true
        working_dir: /usr/app
        command: npm run dev
        ports: 
            - 3000:3000
volumes: 
    nodemodules: {}            